- hosts: localhost
  become: yes
  vars:
    user_name: hiroki
    rbenv_url: https://github.com/sstephenson/rbenv.git
    ruby_build_url: https://github.com/sstephenson/ruby-build.git
    ruby_version: 2.6.4
  tasks:
    - name: check ruby version
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      shell: source ~/.bash_profile; rbenv versions | grep -q "{{ruby_version}}"
      register: is_ruby_installed
      failed_when: is_ruby_installed.rc not in [0, 1]

    - name: install packeges for rbenv and ruby-build
      apt: name="{{item}}" state=present
      with_items:
        - gcc
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - libsqlite3-dev
        - libbz2-dev
        - ruby-dev
        - libffi-dev
        - nodejs
      when: is_ruby_installed.rc == 1

    - name: get rbenv from github
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      git: repo="{{rbenv_url}}" dest=~/.rbenv
      when: is_ruby_installed.rc == 1

    - name: create directory for ruby-build
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      file: path=~/.rbenv/plugins state=directory mode=0755
      when: is_ruby_installed.rc == 1

    - name: get ruby-build from github
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      git: repo="{{ruby_build_url}}" dest=~/.rbenv/plugins/ruby-build
      when: is_ruby_installed.rc == 1

    - name: add rbenv binary PATH
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      lineinfile:
        dest: ~/dotfiles/.bash_profile
        line: "{{item}}"
      with_items:
        - export PATH="$HOME/.rbenv/bin:$PATH"
        - eval "$(rbenv init -)"
      when: is_ruby_installed.rc == 1

    - name: install ruby
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      shell: >
        {{item}}
      with_items:
        - source ~/.bash_profile; rbenv install "{{ruby_version}}"
        - source ~/.bash_profile; rbenv global "{{ruby_version}}"
        - source ~/.bash_profile; eval "$(rbenv init -)"
      when: is_ruby_installed.rc == 1
