- hosts: localhost
  become: yes
  vars:
    user_name: hiroki
    src_dir: /usr/local/src
    tmux_version: 2.9
    tmux_source_url: https://github.com/tmux/tmux/releases/download/{{tmux_version}}/tmux-{{tmux_version}}.tar.gz
  tasks:
    - name: check tmux version
      become: "{{user_name}}"
      remote_user: "{{user_name}}"
      shell: source ~/.bash_profile; tmux -V | grep -q "{{tmux_version}}"
      register: is_tmux_installed
      failed_when: is_tmux_installed.rc not in [0, 1]

    - name: download tmux source file
      get_url:
        url={{tmux_source_url}}
        dest={{src_dir}}/tmux-{{tmux_version}}.tar.gz
      when: is_tmux_installed.rc == 1

    - name: extract tmux source file
      unarchive:
        src={{src_dir}}/tmux-{{tmux_version}}.tar.gz
        dest=/usr/local/src
        copy=no
      when: is_tmux_installed.rc == 1

    - name: install packages for building tmux
      apt: name="{{item}}" state=present
      with_items:
        - make
        - gcc
        - libevent-dev
        - ncurses-dev
      when: is_tmux_installed.rc == 1

    - name: install tmux
      command: >
        {{item}}
        chdir={{src_dir}}/tmux-{{tmux_version}}
        creates=/usr/local/bin/tmux
      with_items:
        - ./configure
        - make
        - make install
      when: is_tmux_installed.rc == 1
