---
- name: Restart the vnc server
  become: true
  ansible.builtin.systemd_service:
    name: tigervncserver@{{ vnc_display }}.service
    state: restarted

- name: Regenerate locales
  become: true
  ansible.builtin.command: locale-gen
  changed_when: true
