- name: install packages for building tmux
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libevent-dev
    - ncurses-dev
    - xsel
    - bison

- name: download tmux source file
  get_url:
    url: "{{tmux_source_url}}"
    dest: "{{src_dir}}/tmux-{{tmux_version}}.tar.gz"

- name: extract tmux source file
  unarchive:
    src: "{{src_dir}}/tmux-{{tmux_version}}.tar.gz"
    dest: /usr/local/src
    copy: no

- name: install tmux
  command: >
    {{item}}
    chdir={{src_dir}}/tmux-{{tmux_version}}
    creates=/usr/local/bin/tmux
  with_items:
    - ./configure --enable-static
    - make
    - make install