- name: install packeges for pybenv
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - gcc
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libbz2-dev
    - libffi-dev
    - lzma-dev
    - python3-dev
    - libpq-dev
    - postgresql
    - postgresql-contrib
    - liblzma-dev
    - openjdk-11-jdk

- name: get pyenv from github
  become: yes
  become_user: "{{user_name}}"
  git:
    repo: "{{pybenv_url}}"
    dest: $HOME/.pyenv

- name: check python version
  become: yes
  become_user: "{{user_name}}"
  shell: export PATH="$HOME/.pyenv/bin:$PATH"; pyenv versions | grep -q "{{python_version}}"
  register: is_python_installed
  failed_when: is_python_installed.rc not in [0, 1]

- name: install python
  become: yes
  become_user: "{{user_name}}"
  shell: >
    {{item}}
  with_items:
    - export PATH="$HOME/.pyenv/bin:$PATH"; eval "$(pyenv init -)"
    - export PATH="$HOME/.pyenv/bin:$PATH"; pyenv install "{{python_version}}"
    - export PATH="$HOME/.pyenv/bin:$PATH"; pyenv global "{{python_version}}"
  when: is_python_installed.rc == 1
