- name: install common packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - git
    - unzip
    - bzip2
    - cmake
    - build-essential
    - pkg-config
    - sqlite3
    - snmp
    - xsel
    - postgresql
    - postgresql-contrib
