- name: add dockers official GPG key
  ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: set up the stable repository
  shell: >
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: apt update
  apt:
      update_cache: yes

- name: install Docker Engine
  apt:
      name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
