- name: install packeges for rbenv and ruby-build
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - gcc
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libbz2-dev
    - ruby-dev
    - libffi-dev
    - libyaml

- name: get rbenv from github
  become: yes
  become_user: "{{user_name}}"
  git:
    repo: "{{rbenv_url}}"
    dest: $HOME/.rbenv

- name: check ruby version
  become: yes
  become_user: "{{user_name}}"
  shell: export PATH="$HOME/.rbenv/bin:$PATH"; rbenv versions | grep -q "{{ruby_version}}"
  register: is_ruby_installed
  failed_when: is_ruby_installed.rc not in [0, 1]

- name: create directory for ruby-build
  become: yes
  become_user: "{{user_name}}"
  file:
    path: $HOME/.rbenv/plugins
    state: directory
    mode: 0755
  when: is_ruby_installed.rc == 1

- name: get ruby-build from github
  become: yes
  become_user: "{{user_name}}"
  git:
    repo: "{{ruby_build_url}}"
    dest: $HOME/.rbenv/plugins/ruby-build
  when: is_ruby_installed.rc == 1

- name: install ruby
  become: yes
  become_user: "{{user_name}}"
  shell: >
    {{item}}
  with_items:
    - export PATH="$HOME/.rbenv/bin:$PATH"; eval "$(rbenv init -)"
    - export PATH="$HOME/.rbenv/bin:$PATH"; rbenv install {{ruby_version}}
    - export PATH="$HOME/.rbenv/bin:$PATH"; rbenv global {{ruby_version}}
    - export PATH="$HOME/.rbenv/bin:$PATH"; rbenv rehash
  when: is_ruby_installed.rc == 1