- name: install packages for building neovim
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libuv1-dev
    - gettext
    - libtool
    - libtool-bin
    - fzf

- name: install packages for neovim plugin (--force-overwrite)
  apt:
    name: "{{item}}"
    state: present
    dpkg_options: "force-overwrite"
  with_items:
    - bat
    - ripgrep

- name: install neovim pynvim
  become: yes
  become_user: "{{user_name}}"
  shell: export PATH="$HOME/.pyenv/bin:$PATH"; eval "$(pyenv init -)"; python -m pip install pynvim

- name: install neovim nodejs
  become: yes
  become_user: "{{ user_name }}"
  shell: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; npm install -g neovim

- name: install neovim ruby
  become: yes
  become_user: "{{ user_name }}"
  shell: export PATH="$HOME/.rbenv/bin:$PATH"; eval "$(rbenv init -)"; gem install neovim

- name: check neovim version
  become: yes
  become_user: "{{user_name}}"
  shell: . ~/.profile; nvim -v | grep -q "NVIM {{neovim_version}}"
  register: is_neovim_installed
  failed_when: is_neovim_installed.rc not in [0, 1]

- name: create neovim source directory
  file:
    path: /usr/local/src/neovim.git
    state: directory
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: 0755
  when: is_neovim_installed.rc == 1

- name: download neovim source file
  git:
    repo: "{{neovim_url}}"
    dest: /usr/local/src/neovim.git
    accept_hostkey: yes
    force: yes
    version: "{{neovim_version}}"
  become: no
  when: is_neovim_installed.rc == 1

- name: install neovim
  command: >
    {{item}}
    chdir=/usr/local/src/neovim.git
    creates=/usr/local/bin/neovim
  with_items:
    - make CMAKE_BUILD_TYPE=Release
    - make distclean
    - make install
  when: is_neovim_installed.rc == 1

- name: download vim-plug
  become: yes
  become_user: "{{user_name}}"
  command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs {{vim_plug_url}}

- name: install diagnostic-languageserver
  become: yes
  become_user: "{{ user_name }}"
  shell: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; yarn global add diagnostic-languageserver

- name: install jedi-language-server
  become: yes
  become_user: "{{ user_name }}"
  shell: export PATH="$HOME/.pyenv/bin:$PATH"; eval "$(pyenv init -)"; pip install jedi-language-server
